name: CI

on: [push]

jobs:
  backend:
    name: Build Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
      - name: Gradle build
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build --no-daemon
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_NAME: ${{ secrets.DB_NAME }}
      - name: Upload reports on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: failure
          path: build/reports/
